name: weatherapp
description: "A new Flutter weather app project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ^3.9.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  lottie: ^3.3.2
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
  uses-material-design: true
